export default {
  'jeraby.collection.title': 'Cranes',
  'jeraby.collection.works.jeraby-29.title': '# Jeraby 29',
  'jeraby.collection.works.jeraby-29.presentationDescription': '60x60x32',
  'jeraby.collection.works.jeraby-29.workDetails.main.text': 'White, gray, light blue.</br>White background with gray. Gray and light blue cranes, rocks, and sky.',
  'jeraby.collection.works.jeraby-29.workDetails.small.text': "I have an idea, I see colors, I paint the background (sometimes in multiple layers), and then I look for colors in fashion magazines. I arrange cranes, place them on the canvas, and change the order and grouping until it's just right.",
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.title': '# Dimensions',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.text': '32 birds',
  'jeraby.collection.works.jeraby-28.title': '# Jeraby 28',
  'jeraby.collection.works.jeraby-28.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-28.workDetails.main.text': 'Blue. Blue. Blue.</br>Blue layer with a brush, blue layer with a spatula, blue cranes.',
  'jeraby.collection.works.jeraby-28.workDetails.small.text': "I have an idea, I see colors, I paint the background (sometimes in multiple layers), and then I look for colors in fashion magazines. I arrange cranes, place them on the canvas, and change the order and grouping until it's just right.",
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.title': '# Dimensions',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.text': '26 birds',
  'jeraby.collection.works.jeraby-26.title': '# Jeraby 26',
  'jeraby.collection.works.jeraby-26.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-26.workDetails.main.text': 'Green.</br>Green. Blue. Gold.</br>Green background painted with a brush, cranes in the colors from the picture with the girl who is looking (do not stare).',
  'jeraby.collection.works.jeraby-26.workDetails.small.text': "I have an idea, I see colors, I paint the background (sometimes in multiple layers), and then I look for colors in fashion magazines. I arrange cranes, place them on the canvas, and change the order and grouping until it's just right.",
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.title': '# Dimensions',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.text': '26 birds',
  'jeraby.collection.works.jeraby-27.title': '# Jeraby 27',
  'jeraby.collection.works.jeraby-27.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-27.workDetails.main.text': 'Red with orange, gold with ochre, and then red with orange again. Spatula.</br>Hot summer. Tomatoes. Brown hair on a yellow coat.',
  'jeraby.collection.works.jeraby-27.workDetails.small.text': "I have an idea, I see colors, I paint the background (sometimes in multiple layers), and then I look for colors in fashion magazines. I arrange cranes, place them on the canvas, and change the order and grouping until it's just right.",
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.title': '# Dimensions',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.text': '26 birds',
  'jeraby.collection.works.jeraby-25.title': '# Jeraby 25',
  'jeraby.collection.works.jeraby-25.presentationDescription': '50x50x39',
  'jeraby.collection.works.jeraby-25.workDetails.main.text': 'White. White with layers of gold. Spatula.</br>Flowers and jewelry in photos on a white background. First, there were cranes, and then the background.',
  'jeraby.collection.works.jeraby-25.workDetails.small.text': "I have an idea, I see colors, I paint the background (sometimes in multiple layers), and then I look for colors in fashion magazines. I arrange cranes, place them on the canvas, and change the order and grouping until it's just right.",
  'jeraby.collection.works.jeraby-25.workDetails.gridItems.1.title': '# Dimensions',
  'jeraby.collection.works.jeraby-25.workDetails.gridItems.1.size': '50x50 cm',
  'jeraby.collection.works.jeraby-25.workDetails.gridItems.1.text': '39 birds',
  'jeraby.collection.works.jeraby-23.title': '# Jeraby 23',
  'jeraby.collection.works.jeraby-23.presentationDescription': '50x50x26',
  'jeraby.collection.works.jeraby-23.workDetails.main.text': "Purple. Dark purple that doesn't seem real.</br>And pink, the color of the Valentino collection and their beautiful full-page ads.",
  'jeraby.collection.works.jeraby-23.workDetails.small.text': "I have an idea, I see colors, I paint the background (sometimes in multiple layers), and then I look for colors in fashion magazines. I arrange cranes, place them on the canvas, and change the order and grouping until it's just right.",
  'jeraby.collection.works.jeraby-23.workDetails.gridItems.1.title': '# Dimensions',
  'jeraby.collection.works.jeraby-23.workDetails.gridItems.1.size': '50x50 cm',
  'jeraby.collection.works.jeraby-23.workDetails.gridItems.1.text': '26 birds',
  'jeraby.collection.works.jeraby-20.title': '# Jeraby 20',
  'jeraby.collection.works.jeraby-20.presentationDescription': '60x60x28',
  'jeraby.collection.works.jeraby-20.workDetails.main.text': "Dark red and dark blue. A spatula on the background.</br>Red and blue. Light red to orange. Blue, lighter and light blue.",
  'jeraby.collection.works.jeraby-20.workDetails.small.text': "I have an idea, I see colors, I paint the background (sometimes in multiple layers), and then I look for colors in fashion magazines. I arrange cranes, place them on the canvas, and change the order and grouping until it's just right.",
  'jeraby.collection.works.jeraby-20.workDetails.gridItems.1.title': '# Dimensions',
  'jeraby.collection.works.jeraby-20.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-20.workDetails.gridItems.1.text': '28 birds',
  'jeraby.collection.works.jeraby-16.title': '# Jeraby 16',
  'jeraby.collection.works.jeraby-16.presentationDescription': '60x60x34',
  'jeraby.collection.works.jeraby-16.workDetails.main.text': "Golden with golden. In two layers.</br>Blue, gold, purple. Gustav: Danae, Judith I.",
  'jeraby.collection.works.jeraby-16.workDetails.small.text': "I have an idea, I see colors, I paint the background (sometimes in multiple layers), and then I look for colors in fashion magazines. I arrange cranes, place them on the canvas, and change the order and grouping until it's just right.",
  'jeraby.collection.works.jeraby-16.workDetails.gridItems.1.title': '# Dimensions',
  'jeraby.collection.works.jeraby-16.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-16.workDetails.gridItems.1.text': '34 birds',
  'jeraby.collection.works.jeraby-15.title': '# Jeraby 15',
  'jeraby.collection.works.jeraby-15.presentationDescription': '60x60x37',
  'jeraby.collection.works.jeraby-15.workDetails.main.text': "Red. Crimson. A drop of brown. With a brush.</br>A golden drop.</br>The golden ratio.</br>Golden and red cranes.",
  'jeraby.collection.works.jeraby-15.workDetails.small.text': "I have an idea, I see colors, I paint the background (sometimes in multiple layers), and then I look for colors in fashion magazines. I arrange cranes, place them on the canvas, and change the order and grouping until it's just right.",
  'jeraby.collection.works.jeraby-15.workDetails.gridItems.1.title': '# Dimensions',
  'jeraby.collection.works.jeraby-15.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-15.workDetails.gridItems.1.text': '37 birds',
  'jeraby.collection.works.jeraby-7.title': '# Jeraby 7',
  'jeraby.collection.works.jeraby-7.presentationDescription': '50x50x42',
  'jeraby.collection.works.jeraby-7.workDetails.main.text': "White. White Saturday. Easter.</br>Red and yellow cranes. Flowers in the photos.",
  'jeraby.collection.works.jeraby-7.workDetails.small.text': "I have an idea, I see colors, I paint the background (sometimes in multiple layers), and then I look for colors in fashion magazines. I arrange cranes, place them on the canvas, and change the order and grouping until it's just right.",
  'jeraby.collection.works.jeraby-7.workDetails.gridItems.1.title': '# Dimensions',
  'jeraby.collection.works.jeraby-7.workDetails.gridItems.1.size': '50x50 cm',
  'jeraby.collection.works.jeraby-7.workDetails.gridItems.1.text': '42 birds',
}