export default {
  'modal.work.contact.available.description': 'This work is still available, but this is not a binding offer. We will contact you as soon as possible to discuss the details.',
  'modal.work.contact.unavailable.description': 'This work is no longer available, but let us know that you are interested in a similar work. We will contact you as soon as possible to discuss the details.',
  'modal.work.contact.name': 'Name',
  'modal.work.contact.surname': 'Surname',
  'modal.work.contact.email': 'Email',
  'modal.work.contact.phone': 'Phone',
  'modal.work.contact.message': 'Message',
  'modal.work.contact.submit': 'Submit',
  'modal.work.contact.validation.name': 'Please enter your name',
  'modal.work.contact.validation.surname': 'Please enter your surname',
  'modal.work.contact.validation.email': 'Please enter your email',
  'modal.work.contact.validation.phone': 'Please enter your phone',
  'modal.work.contact.validation.message': 'Please enter your message',
  'modal.contact.message.sent.success': 'Your message has been sent successfully.',
  'modal.contact.message.thank.you': "Thank you for contacting us!",
  'cta.button.processing': "Sending",
  'sending.error': 'Something went wrong. Please try it again later.',
  'contact.form': 'Please leave me a message',
  'contact.title': 'Contact',
  'contact.main.text': "If you contact me, you will make my day much better. But if you don't maybe somebody else will",
  'contact.small.text': "If you have any message or question for me, please use this contact form. And of course you can use it for questions or demands for a specific works, but it is much easier for you to do this from the work detail or from the work presentation on the home/collection page where you can hit the black button which opens a contact form as well but we now which work your inquiry is related to without you having to specify it."
}