export default {
  'jeraby.collection.title': 'Jeřáby',
  'jeraby.collection.works.jeraby-29.title': '# Jeraby 29',
  'jeraby.collection.works.jeraby-29.presentationDescription': '60x60x32',
  'jeraby.collection.works.jeraby-29.workDetails.main.text': 'Bílá, šedá, světle modrá.</br>Podklad bílá se šedou. Šedé a světle modré jeřáby, skály a nebe.',
  'jeraby.collection.works.jeraby-29.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.text': '32 ptáků',
  'jeraby.collection.works.jeraby-28.title': '# Jeraby 28',
  'jeraby.collection.works.jeraby-28.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-28.workDetails.main.text': 'Modrá. Modrá. Modrá.</br>Modrá vrstva štětcem, modrá vrstva špachtlí, modré jeřáby.',
  'jeraby.collection.works.jeraby-28.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-26.title': '# Jeraby 26',
  'jeraby.collection.works.jeraby-26.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-26.workDetails.main.text': 'Zelená.</br>Zelená. Modrá. Zlatá.</br>Zelený podklad nabouchaný štětcem, jeřáby v barvách z obrázku s děvčetem, co kouká (nečum).',
  'jeraby.collection.works.jeraby-26.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-27.title': '# Jeraby 27',
  'jeraby.collection.works.jeraby-27.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-27.workDetails.main.text': 'Červená s oranžovou, zlatá s okrovou a pak znovu červená s oranžovou. Špachtle.</br>Horké léto. Rajčata. Hnědé vlasy na žlutém kabátě.',
  'jeraby.collection.works.jeraby-27.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-25.title': '# Jeraby 25',
  'jeraby.collection.works.jeraby-25.presentationDescription': '50x50x39',
  'jeraby.collection.works.jeraby-25.workDetails.main.text': 'Bílá. Bílá se zlatou ve vrstvách. Špachtle.</br>Květy a šperky na fotkách na bílém pozadí. Nejdřív byly jeřáby a pak k nim pozadí.',
  'jeraby.collection.works.jeraby-25.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-25.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-25.workDetails.gridItems.1.size': '50x50 cm',
  'jeraby.collection.works.jeraby-25.workDetails.gridItems.1.text': '39 ptáků',
  'jeraby.collection.works.jeraby-23.title': '# Jeraby 23',
  'jeraby.collection.works.jeraby-23.presentationDescription': '50x50x26',
  'jeraby.collection.works.jeraby-23.workDetails.main.text': 'Fialová. Tmavá fialová co se nezdá.</br>A růžová, pink, barva kolekce a krásných celostránkových reklam Valentino.',
  'jeraby.collection.works.jeraby-23.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-23.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-23.workDetails.gridItems.1.size': '50x50 cm',
  'jeraby.collection.works.jeraby-23.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-20.title': '# Jeraby 20',
  'jeraby.collection.works.jeraby-20.presentationDescription': '60x60x28',
  'jeraby.collection.works.jeraby-20.workDetails.main.text': 'Tmavě červená a tmavě modrá. Špachtlí na pozadí.</br>Červená a modrá. Světle červená až oranžová. Modrá, světlejší a světle modrá.',
  'jeraby.collection.works.jeraby-20.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-20.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-20.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-20.workDetails.gridItems.1.text': '28 ptáků',
  'jeraby.collection.works.jeraby-16.title': '# Jeraby 16',
  'jeraby.collection.works.jeraby-16.presentationDescription': '60x60x34',
  'jeraby.collection.works.jeraby-16.workDetails.main.text': 'Zlatá se zlatou. Ve dvou vrstvách.</br>Modrá, zlatá, fialová. Gustav : Danaé, Judit I.',
  'jeraby.collection.works.jeraby-16.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-16.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-16.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-16.workDetails.gridItems.1.text': '34 ptáků',
  'jeraby.collection.works.jeraby-15.title': '# Jeraby 15',
  'jeraby.collection.works.jeraby-15.presentationDescription': '60x60x37',
  'jeraby.collection.works.jeraby-15.workDetails.main.text': 'Červená. Rudá. Kapka hnědé. Štětcem.</br>Zlatá kapka.</br>Zlatý řez. </br>Zlaté a červené jeřáby',
  'jeraby.collection.works.jeraby-15.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-15.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-15.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-15.workDetails.gridItems.1.text': '37 ptáků',
  'jeraby.collection.works.jeraby-7.title': '# Jeraby 7',
  'jeraby.collection.works.jeraby-7.presentationDescription': '50x50x42',
  'jeraby.collection.works.jeraby-7.workDetails.main.text': 'Bilá. Bílá sobota. Velikonoce.</br>Červené a žluté jeřáby. Kytky na fotkách.',
  'jeraby.collection.works.jeraby-7.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-7.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-7.workDetails.gridItems.1.size': '50x50 cm',
  'jeraby.collection.works.jeraby-7.workDetails.gridItems.1.text': '42 ptáků',
  'jeraby.collection.works.jeraby-6.title': '# Jeraby 6',
  'jeraby.collection.works.jeraby-6.presentationDescription': '50x50x26',
  'jeraby.collection.works.jeraby-6.workDetails.main.text': 'Červená s modrou špachtlí.</br>Modrá, červená a žlutá v různých kombinacích na jeřábech.',
  'jeraby.collection.works.jeraby-6.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-6.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-6.workDetails.gridItems.1.size': '50x50 cm',
  'jeraby.collection.works.jeraby-6.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-18.title': '# Jeraby 18',
  'jeraby.collection.works.jeraby-18.presentationDescription': '60x60x18',
  'jeraby.collection.works.jeraby-18.workDetails.main.text': 'Bílá se šedou. Modré jeřáby.</br>Bílá, šedá, modrá. Barvy vody, ledu, ledovců.',
  'jeraby.collection.works.jeraby-18.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-18.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-18.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-18.workDetails.gridItems.1.text': '18 ptáků',
  'jeraby.collection.works.jeraby-17.title': '# Jeraby 17',
  'jeraby.collection.works.jeraby-17.presentationDescription': '50x50x34',
  'jeraby.collection.works.jeraby-17.workDetails.main.text': 'Červená se zlatou, štětcem.</br>Jeřáby dle barev Vincenta a jeho Italky.',
  'jeraby.collection.works.jeraby-17.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-17.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-17.workDetails.gridItems.1.size': '50x50 cm',
  'jeraby.collection.works.jeraby-17.workDetails.gridItems.1.text': '34 ptáků',
  'jeraby.collection.works.jeraby-14.title': '# Jeraby 14',
  'jeraby.collection.works.jeraby-14.presentationDescription': '80x80x53',
  'jeraby.collection.works.jeraby-14.workDetails.main.text': 'Modrá bílá. Modrá štětcem. Modrá bilá. Modrá bílá špachtlí.</br>Modrá se žlutou a modrá s červenou na jeřábech.',
  'jeraby.collection.works.jeraby-14.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-14.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-14.workDetails.gridItems.1.size': '80x80 cm',
  'jeraby.collection.works.jeraby-14.workDetails.gridItems.1.text': '53 ptáků',
  'jeraby.collection.works.jeraby-21.title': '# Jeraby 21',
  'jeraby.collection.works.jeraby-21.presentationDescription': '70x70x30',
  'jeraby.collection.works.jeraby-21.workDetails.main.text': 'Zakázka.</br>Dva pokoje, dva obrazy.</br>Zadání klienta: Bílo zlatý podklad.',
  'jeraby.collection.works.jeraby-21.workDetails.small.text': 'Na zakázku, dle přání klienta. Doplněk interiéru zrekonstruovaného pokoje v penzionu. Dva pokoje, dva obrazy. Stejný styl, ale každý jiný. Zadání bylo, aby obraz barevně nevyčníval, ale vizuálně doplnil zařízení pokoje. Na jeřáby jsou použité stránky z časopisu INTRO, který je tištěný na matnou křídu a díky tomu jsou barvy tlumenější.',
  'jeraby.collection.works.jeraby-21.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-21.workDetails.gridItems.1.size': '70x70 cm',
  'jeraby.collection.works.jeraby-21.workDetails.gridItems.1.text': '30 ptáků',
}