export default {
  'jeraby.collection.title': 'Jeřáby',
  'jeraby.collection.works.jeraby-29.title': '# Jeraby 29',
  'jeraby.collection.works.jeraby-29.presentationDescription': '60x60x32',
  'jeraby.collection.works.jeraby-29.workDetails.main.text': 'Bílá, šedá, světle modrá.</br>Podklad bílá se šedou. Šedé a světle modré jeřáby, skály a nebe.',
  'jeraby.collection.works.jeraby-29.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.text': '32 ptáků',
  'jeraby.collection.works.jeraby-28.title': '# Jeraby 28',
  'jeraby.collection.works.jeraby-28.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-28.workDetails.main.text': 'Modrá. Modrá. Modrá.</br>Modrá vrstva štětcem, modrá vrstva špachtlí, modré jeřáby.',
  'jeraby.collection.works.jeraby-28.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-26.title': '# Jeraby 26',
  'jeraby.collection.works.jeraby-26.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-26.workDetails.main.text': 'Zelená.</br>Zelená. Modrá. Zlatá.</br>Zelený podklad nabouchaný štětcem, jeřáby v barvách z obrázku s děvčetem, co kouká (nečum).',
  'jeraby.collection.works.jeraby-26.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-27.title': '# Jeraby 27',
  'jeraby.collection.works.jeraby-27.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-27.workDetails.main.text': 'Červená s oranžovou, zlatá s okrovou a pak znovu červená s oranžovou. Špachtle.</br>Horké léto. Rajčata. Hnědé vlasy na žlutém kabátě.',
  'jeraby.collection.works.jeraby-27.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-25.title': '# Jeraby 25',
  'jeraby.collection.works.jeraby-25.presentationDescription': '50x50x39',
  'jeraby.collection.works.jeraby-25.workDetails.main.text': 'Bílá. Bílá se zlatou ve vrstvách. Špachtle.</br>Květy a šperky na fotkách na bílém pozadí. Nejdřív byly jeřáby a pak k nim pozadí.',
  'jeraby.collection.works.jeraby-25.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-25.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-25.workDetails.gridItems.1.size': '50x50 cm',
  'jeraby.collection.works.jeraby-25.workDetails.gridItems.1.text': '39 ptáků',
  'jeraby.collection.works.jeraby-23.title': '# Jeraby 23',
  'jeraby.collection.works.jeraby-23.presentationDescription': '50x50x26',
  'jeraby.collection.works.jeraby-23.workDetails.main.text': 'Fialová. Tmavá fialová co se nezdá.</br>A růžová, pink, barva kolekce a krásných celostránkových reklam Valentino.',
  'jeraby.collection.works.jeraby-23.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-23.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-23.workDetails.gridItems.1.size': '50x50 cm',
  'jeraby.collection.works.jeraby-23.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-20.title': '# Jeraby 20',
  'jeraby.collection.works.jeraby-20.presentationDescription': '60x60x28',
  'jeraby.collection.works.jeraby-20.workDetails.main.text': 'Tmavě červená a tmavě modrá. Špachtlí na pozadí.</br>Červená a modrá. Světle červená až oranžová. Modrá, světlejší a světle modrá.',
  'jeraby.collection.works.jeraby-20.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-20.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-20.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-20.workDetails.gridItems.1.text': '28 ptáků',
  'jeraby.collection.works.jeraby-16.title': '# Jeraby 16',
  'jeraby.collection.works.jeraby-16.presentationDescription': '60x60x34',
  'jeraby.collection.works.jeraby-16.workDetails.main.text': 'Zlatá se zlatou. Ve dvou vrstvách.</br>Modrá, zlatá, fialová. Gustav : Danaé, Judit I.',
  'jeraby.collection.works.jeraby-16.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-16.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-16.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-16.workDetails.gridItems.1.text': '34 ptáků',
  'jeraby.collection.works.jeraby-15.title': '# Jeraby 15',
  'jeraby.collection.works.jeraby-15.presentationDescription': '60x60x37',
  'jeraby.collection.works.jeraby-15.workDetails.main.text': 'Červená. Rudá. Kapka hnědé. Štětcem.</br>Zlatá kapka.</br>Zlatý řez. </br>Zlaté a červené jeřáby',
  'jeraby.collection.works.jeraby-15.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-15.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-15.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-15.workDetails.gridItems.1.text': '37 ptáků',
}