export default {
  'jeraby.collection.title': 'Jeřáby',
  'jeraby.collection.works.jeraby-29.title': '# Jeraby 29',
  'jeraby.collection.works.jeraby-29.presentationDescription': '60x60x32',
  'jeraby.collection.works.jeraby-29.workDetails.main.text': 'Bílá, šedá, světle modrá.</br>Podklad bílá se šedou. Šedé a světle modré jeřáby, skály a nebe.',
  'jeraby.collection.works.jeraby-29.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-29.workDetails.gridItems.1.text': '32 ptáků',
  'jeraby.collection.works.jeraby-28.title': '# Jeraby 28',
  'jeraby.collection.works.jeraby-28.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-28.workDetails.main.text': 'Modrá. Modrá. Modrá.</br>Modrá vrstva štětcem, modrá vrstva špachtlí, modré jeřáby.',
  'jeraby.collection.works.jeraby-28.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-28.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-26.title': '# Jeraby 26',
  'jeraby.collection.works.jeraby-26.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-26.workDetails.main.text': 'Zelená.</br>Zelená. Modrá. Zlatá.</br>Zelený podklad nabouchaný štětcem, jeřáby v barvách z obrázku s děvčetem, co kouká (nečum).',
  'jeraby.collection.works.jeraby-26.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-26.workDetails.gridItems.1.text': '26 ptáků',
  'jeraby.collection.works.jeraby-27.title': '# Jeraby 27',
  'jeraby.collection.works.jeraby-27.presentationDescription': '60x60x26',
  'jeraby.collection.works.jeraby-27.workDetails.main.text': 'Červená s oranžovou, zlatá s okrovou a pak znovu červená s oranžovou. Špachtle.</br>Horké léto. Rajčata. Hnědé vlasy na žlutém kabátě.',
  'jeraby.collection.works.jeraby-27.workDetails.small.text': 'Mám nápad, vidím barvy, namaluju podklad (někdy ve více vrstvách) a pak k němu v módních časopisech hledám barvy. Naskládám jeřáby, pokládám je na plátno a měním pořadí a seskupení dokud to není ono.',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.title': '# Rozměry',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.size': '60x60 cm',
  'jeraby.collection.works.jeraby-27.workDetails.gridItems.1.text': '26 ptáků',
}