export default {
  'modal.work.contact.available.description': 'Tato práce je stále k dispozici, ale toto není závazná nabídka. Budeme vás kontaktovat co nejdříve, abychom mohli probrat detaily.',
  'modal.work.contact.sold.description': 'Tato práce již není k dispozici, ale dejte nám vědět, pokud máte zájem o podobné dílo. Budeme vás kontaktovat co nejdříve, abychom mohli probrat detaily.',
  'modal.work.contact.name': 'Jméno',
  'modal.work.contact.surname': 'Příjmení',
  'modal.work.contact.email': 'Email',
  'modal.work.contact.phone': 'Telefon',
  'modal.work.contact.message': 'Zpráva',
  'modal.work.contact.submit': 'Odeslat',
  'modal.work.contact.validation.name': 'Zadejte prosím své jméno',
  'modal.work.contact.validation.surname': 'Zadejte prosím své příjmení',
  'modal.work.contact.validation.email': 'Zadejte prosím svůj email',
  'modal.work.contact.validation.phone': 'Zadejte prosím svůj telefon',
  'modal.work.contact.validation.message': 'Zadejte prosím svou zprávu',
}