export default {
  'jeraby.collection.title': 'Cranes',
  'jeraby.collection.works.jeraby-1.title': 'Jeraby 1',
  'jeraby.collection.works.jeraby-1.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-2.title': 'Jeraby 2',
  'jeraby.collection.works.jeraby-2.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-3.title': 'Jeraby 3',
  'jeraby.collection.works.jeraby-3.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-4.title': 'Jeraby 4',
  'jeraby.collection.works.jeraby-4.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-5.title': 'Jeraby 5',
  'jeraby.collection.works.jeraby-5.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-6.title': 'Jeraby 6',
  'jeraby.collection.works.jeraby-6.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-7.title': 'Jeraby 7',
  'jeraby.collection.works.jeraby-7.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-8.title': 'Jeraby 8',
  'jeraby.collection.works.jeraby-8.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-9.title': 'Jeraby 9',
  'jeraby.collection.works.jeraby-9.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-10.title': 'Jeraby 10',
  'jeraby.collection.works.jeraby-10.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-11.title': 'Jeraby 11',
  'jeraby.collection.works.jeraby-11.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-12.title': 'Jeraby 12',
  'jeraby.collection.works.jeraby-12.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-13.title': 'Jeraby 13',
  'jeraby.collection.works.jeraby-13.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-14.title': 'Jeraby 14',
  'jeraby.collection.works.jeraby-14.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-15.title': 'Jeraby 15',
  'jeraby.collection.works.jeraby-15.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-16.title': 'Jeraby 16',
  'jeraby.collection.works.jeraby-16.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-17.title': 'Jeraby 17',
  'jeraby.collection.works.jeraby-17.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-18.title': 'Jeraby 18',
  'jeraby.collection.works.jeraby-18.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-19.title': 'Jeraby 19',
  'jeraby.collection.works.jeraby-19.presentationDescription': 'Jeraby 1 desc something on this is another line',
  'jeraby.collection.works.jeraby-20.title': 'Jeraby 20',
  'jeraby.collection.works.jeraby-20.presentationDescription': 'Jeraby 1 desc something on this is another line',
}