/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowLeftRigt: typeof import('./components/ArrowLeftRigt.vue')['default']
    BurgerButton: typeof import('./components/BurgerButton.vue')['default']
    ContactForm: typeof import('./components/ContactForm.vue')['default']
    CtaButton: typeof import('./components/CtaButton.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    Grid: typeof import('./components/Grid.vue')['default']
    HomeButton: typeof import('./components/HomeButton.vue')['default']
    Link: typeof import('./components/Link.vue')['default']
    LinkButton: typeof import('./components/LinkButton.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModalContactError: typeof import('./components/ModalContactError.vue')['default']
    ModalContactSuccess: typeof import('./components/ModalContactSuccess.vue')['default']
    ModalView: typeof import('./components/ModalView.vue')['default']
    ModalWorkContact: typeof import('./components/ModalWorkContact.vue')['default']
    ModalWorkDetailGallery: typeof import('./components/ModalWorkDetailGallery.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NavScrollWatcher: typeof import('./components/NavScrollWatcher.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollButton: typeof import('./components/ScrollButton.vue')['default']
    StInput: typeof import('./components/StInput.vue')['default']
    StTextArea: typeof import('./components/StTextArea.vue')['default']
    WorkOverview: typeof import('./components/WorkOverview.vue')['default']
    WorkOverviewSummary: typeof import('./components/WorkOverviewSummary.vue')['default']
    WorksOverviewList: typeof import('./components/WorksOverviewList.vue')['default']
  }
}
